In [1]:
from statistic import Statistic

In [2]:
sample_data = Statistic("data/student_dataset_300.xlsx")
sample_data.data

,Student_ID,Name,Gender,Age,Grade_Level,Math,English,Reading,Science,History,Attendance_%,Study_Hours_Per_Week,Extracurricular,Parent_Education,GPA
0,1,Nguyen Thao Han,Male,16,10,58,97,56,93,97,97.3,3,No,High School,8.02
1,2,Tran Ha Hai,Male,15,12,62,95,91,94,84,85.5,15,No,High School,8.52
2,3,Dang Khang Han,Male,16,10,98,71,56,55,74,77.4,12,No,High School,7.08
3,4,Tran Yen Long,Female,15,12,68,90,89,73,86,79.8,3,Yes,College,8.12
4,5,Tran Viet Hai,Female,15,11,67,79,90,73,60,84.3,7,No,High School,7.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,Huynh Trang Ha,Female,16,11,51,64,64,96,58,80.3,1,Yes,High School,6.66
296,297,Nguyen Long Vy,Female,17,12,89,53,88,53,92,77.7,1,Yes,High School,7.50
297,298,Bui Long Dung,Female,17,11,94,59,63,94,93,90.8,10,No,High School,8.06
298,299,Le Mai Tung,Female,15,12,96,89,57,68,57,94.6,16,Yes,PhD,7.34
299,300,Vo Tung Ngan,Male,16,11,95,76,68,60,52,88.7,7,No,Bachelor,7.02

In [3]:
sample_data.process_query("Show me the highest math score")

,Student_ID,Name,Gender,Age,Grade_Level,Math,English,Reading,Science,History,Attendance_%,Study_Hours_Per_Week,Extracurricular,Parent_Education,GPA
91,92,Bui Ngan Hai,Male,15,12,100,92,83,69,79,91.1,1,Yes,Master,8.46